version: '3.3'
services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'MLE_LAB_3'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'artem'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'artem'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '6603:3306'
    expose:
      # Opens port 3306 on the container
      - '6603'
      # Where our data will be persisted
    volumes:
      ["/root/docker/[container_name]/conf.d", "/etc/mysql/conf.d"]